import { useEffect, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { Plus, Minus, LocateFixed, ArrowUpRight, Truck, Layers, MapPin, X, Navigation, Clock, Package } from 'lucide-react';
import { mexicoStates } from '@/lib/mexico-map';
import { operations, medicines, incidents, autoAlerts, trackingFor, carriers, type Operation } from '@/lib/elia-data';
import { Button, StatusBadge, ProgressBar, Timeline, LogisticsTags } from './ui';
const cities=[{name:'Monterrey',lon:-100.31,lat:25.68},{name:'Guadalajara',lon:-103.35,lat:20.67},{name:'Ciudad de México',lon:-99.13,lat:19.43},{name:'Puebla',lon:-98.2,lat:19.04},{name:'Veracruz',lon:-96.13,lat:19.17},{name:'Villahermosa',lon:-92.95,lat:17.99},{name:'Mérida',lon:-89.59,lat:20.97},{name:'Cancún',lon:-86.85,lat:21.16}] as const;
const xy=(lon:number,lat:number):[number,number]=>[(lon+118.5)*29,(33-lat)*32];
const routes=[{from:2,to:7,index:0,tone:'normal'},{from:1,to:0,index:1,tone:'normal'},{from:2,to:4,index:2,tone:'attention'},{from:5,to:6,index:3,tone:'critical'}] as const;
const filters=[{label:'Todas',tone:'all'},{label:'Normales',tone:'normal'},{label:'Atención',tone:'attention'},{label:'Críticas',tone:'critical'}];
function visibleRoutes(filter:string,carrier='Todos'){return routes.filter(r=>(carrier==='Todos'||trackingFor(operations[r.index].folio).carrier===carrier)).filter(r=>filter==='Todas'||(filter==='Normales'&&r.tone==='normal')||(filter==='Atención'&&r.tone==='attention')||(filter==='Críticas'&&r.tone==='critical'));}
export function MexicoMap({selected=null,onSelect,filter='Todas',carrier='Todos'}:{selected?:number|null;onSelect?:(i:number)=>void;filter?:string;carrier?:string}) {
 const [zoom,setZoom]=useState(1);
 return <div className="mexico-map"><div className="map-context"><span className="map-country">MÉXICO</span><span>Red nacional de distribución</span></div><div className="map-ocean ocean-pacific">OCÉANO PACÍFICO</div><div className="map-ocean ocean-gulf">GOLFO DE MÉXICO</div>
 <svg viewBox="0 0 980 580" aria-label="Mapa de México con rutas de distribución de medicamentos" className="mexico-svg"><g transform={`translate(${490-490*zoom},${290-290*zoom}) scale(${zoom})`}>{mexicoStates.map((s,i)=><path key={i} d={s.d} className="mexico-state"/>)}<text x="435" y="204" className="map-region-label">MÉXICO</text>
 {visibleRoutes(filter,carrier).map(r=>{const a=cities[r.from],b=cities[r.to],op=operations[r.index];const [x1,y1]=xy(a.lon,a.lat),[x2,y2]=xy(b.lon,b.lat);const cx=(x1+x2)/2,cy=(y1+y2)/2-35;const t=op.progress/100;const x=(1-t)**2*x1+2*(1-t)*t*cx+t*t*x2;const y=(1-t)**2*y1+2*(1-t)*t*cy+t*t*y2;const d=`M${x1},${y1} Q${cx},${cy} ${x2},${y2}`;
 return <g key={r.index} className={`map-route ${r.tone} ${selected===r.index?'selected':''} ${selected!==null&&selected!==r.index?'muted-route':''}`} onClick={()=>onSelect?.(r.index)} role="button" tabIndex={0} aria-label={`Seleccionar ruta ${op.route}`} aria-pressed={selected===r.index} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect?.(r.index)}}}><title>{`${op.route} · ${trackingFor(op.folio).carrier} · ETA ${trackingFor(op.folio).eta}`}</title><path d={d} className="route-track"/><path d={d} pathLength="100" strokeDasharray={`${op.progress} 100`} className="route-progress"/><path d={d} className="route-hit"/><g transform={`translate(${x},${y})`} className="vehicle-marker"><circle r="12" className="vehicle-background"/><Truck x={-7} y={-7} width={14} height={14} className="vehicle-icon"/><rect x="-17" y="17" width="34" height="18" rx="4" className="route-label-background"/><text x="0" y="29" textAnchor="middle" className="route-progress-label">{op.progress}%</text>{selected===r.index&&<g className="map-callout"><g transform={`translate(${x>720?-160:0},0)`}><rect x="16" y="-36" width="128" height="34" rx="4"/><text x="24" y="-22">{trackingFor(op.folio).lastLocation}</text><text x="24" y="-9" className="callout-sub">{`${trackingFor(op.folio).carrier} · ETA ${trackingFor(op.folio).eta}`}</text></g></g>}</g></g>})}
 {cities.map((c,i)=>{const [x,y]=xy(c.lon,c.lat);return <g key={c.name} className="map-city"><circle cx={x} cy={y} r={i===2?10:7} className={`city-halo ${i===5?'critical':i===4?'attention':''}`}/><circle cx={x} cy={y} r={i===2?5:3.5} className={`city-dot ${i===5?'critical':i===4?'attention':''}`}/><text x={x+(i===7?12:i===6?-12:i===3?16:0)} y={y+(i===2?26:i===3?42:i===4?27:i===5?24:-16)} textAnchor={i===7||i===3?'start':i===6?'end':'middle'}>{c.name}</text></g>})}</g></svg>
 <div className="map-zoom"><Button size="icon" variant="ghost" aria-label="Acercar mapa" title="Acercar" onClick={()=>setZoom(Math.min(zoom+.2,1.6))}><Plus/></Button><Button size="icon" variant="ghost" aria-label="Alejar mapa" title="Alejar" onClick={()=>setZoom(Math.max(zoom-.2,.8))}><Minus/></Button><span/><Button size="icon" variant="ghost" aria-label="Centrar mapa" title="Centrar mapa" onClick={()=>setZoom(1)}><LocateFixed/></Button></div>
 <div className="map-legend"><span><i className="legend-dot normal"/>Normal</span><span><i className="legend-dot attention"/>Atención</span><span><i className="legend-dot critical"/>Crítica</span><span className="legend-node"><Truck size={12}/>Unidad en tránsito</span></div><div className="map-scale"><span/>100 km</div></div>;
}
function RouteDossier({operation,onClose}:{operation:Operation;onClose:()=>void}){const cargo=medicines.filter(m=>m.folio===operation.folio);const t=trackingFor(operation.folio);const opAlerts=[...incidents.filter(i=>i.folio===operation.folio).map(i=>i.type),...autoAlerts.filter(a=>a.folio===operation.folio).map(a=>a.type)];const uniqueAlerts=[...new Set(opAlerts)];return <section className="route-dossier" aria-label="Detalle de ruta seleccionada"><div className="dossier-heading"><div><span className="eyebrow">TRAZABILIDAD DE RUTA</span><h3>{operation.folio}</h3></div><Button size="icon" variant="ghost" onClick={onClose} aria-label="Cerrar detalle de ruta"><X/></Button></div><StatusBadge status={operation.status}/><LogisticsTags operation={operation}/><dl className="dossier-summary"><div><dt><Navigation size={12}/>Ruta</dt><dd>{operation.origin} → {operation.destination}</dd></div><div><dt>Operador logístico</dt><dd>{t.carrier} · {operation.operator}</dd></div><div><dt>Estado estándar</dt><dd>{t.unified}</dd></div><div><dt><MapPin size={12}/>Última ubicación</dt><dd>{t.lastLocation}</dd></div><div><dt>Última actualización</dt><dd>{t.lastUpdate} · {t.source}</dd></div><div><dt><Clock size={12}/>ETA</dt><dd>{t.eta}</dd></div></dl><div className="dossier-progress"><span>Avance de ruta</span><ProgressBar value={operation.progress}/></div><section className="dossier-alerts"><h4>Incidencias y alertas <span>{uniqueAlerts.length}</span></h4>{uniqueAlerts.length?uniqueAlerts.slice(0,3).map(a=><p key={a}><i className="legend-dot critical"/>{a}</p>):<p className="muted"><i className="legend-dot normal"/>Sin incidencias registradas</p>}</section><section className="dossier-cargo"><h4><Package size={13}/>Medicamentos en tránsito <span>{cargo.length}</span></h4>{cargo.map(m=><div key={m.lot}><strong>{m.name}</strong><span>{m.quantity}</span><small>Lote {m.lot}</small></div>)}</section><section className="dossier-timeline"><h4>Eventos de la operación</h4><Timeline operation={operation}/></section><Button asChild variant="outline" className="dossier-link"><Link to="/operaciones/$folio" params={{folio:operation.folio}}>Abrir expediente<ArrowUpRight/></Link></Button></section>}
export function MapPanel({expanded=false,routeSelection,onSelectionChange}:{expanded?:boolean;routeSelection?:number|null;onSelectionChange?:(i:number|null)=>void}) {
 const [localSelected,setLocalSelected]=useState<number|null>(null);const [filter,setFilter]=useState('Todas');const [carrier,setCarrier]=useState('Todos');const selected=routeSelection===undefined?localSelected:routeSelection;const select=(i:number|null)=>{setLocalSelected(i);onSelectionChange?.(i)};const op=selected===null?null:operations[selected];const shown=visibleRoutes(filter,carrier);
 useEffect(()=>{if(selected!==null&&!visibleRoutes(filter,carrier).some(r=>r.index===selected)){setFilter('Todas');setCarrier('Todos')}},[selected]);
 const changeFilter=(f:string)=>{setFilter(f);if(selected!==null&&!visibleRoutes(f,carrier).some(r=>r.index===selected))select(null)};const changeCarrier=(c:string)=>{setCarrier(c);if(selected!==null&&!visibleRoutes(filter,c).some(r=>r.index===selected))select(null)};
 return <div className={`map-panel control-map ${expanded?'expanded':''} ${op?'has-selection':''}`}><div className="map-panel-heading"><div><Layers size={17}/><h2>{expanded?'Red logística nacional':'Panorama de la red logística'}</h2><span className="map-heading-note">28 operaciones en seguimiento</span></div><span className="live-indicator"><i/>Actualizado 12:30 h</span></div><div className="map-state-toolbar"><div className="map-filters">{filters.map(t=><Button size="sm" variant="ghost" key={t.label} aria-pressed={filter===t.label} className={`traffic-filter ${filter===t.label?'filter-active':''}`} onClick={()=>changeFilter(t.label)}>{t.tone!=='all'&&<i className={`legend-dot ${t.tone}`}/>} {t.label}<span>{visibleRoutes(t.label,carrier).length}</span></Button>)}</div><label className="carrier-select"><span>Operador</span><select value={carrier} onChange={e=>changeCarrier(e.target.value)} aria-label="Filtrar por operador logístico"><option>Todos</option>{carriers.map(c=><option key={c}>{c}</option>)}</select></label><span className="map-visible-count">{shown.length} rutas visibles</span></div>
 <div className="map-panel-body"><MexicoMap selected={selected} onSelect={select} filter={filter} carrier={carrier}/><aside className="network-panel">{op?<RouteDossier operation={op} onClose={()=>select(null)}/>:<><div className="network-title"><h3>Estado de la red</h3><span className="live-label">EN VIVO</span></div><div className="network-counts"><div><i className="legend-dot normal"/><span>Operaciones normales</span><strong>23</strong></div><div><i className="legend-dot attention"/><span>Requieren atención</span><strong>4</strong></div><div><i className="legend-dot critical"/><span>Operación crítica</span><strong>1</strong></div></div><div className="network-distribution"><i/><i/><i/></div>
 {expanded?<><div className="deliveries-title"><h3>Rutas activas</h3><span>{String(shown.length).padStart(2,'0')}</span></div><div className="active-route-list">{shown.map(r=><Button variant="ghost" key={r.index} className="active-route" onClick={()=>select(r.index)}><span className={`route-symbol ${r.tone}`}><Truck size={16}/></span><span><strong>{operations[r.index].route}</strong><small>{trackingFor(operations[r.index].folio).carrier} · ETA {trackingFor(operations[r.index].folio).eta} · {operations[r.index].progress}%</small></span><ArrowUpRight size={14}/></Button>)}</div></>:<><div className="deliveries-title"><h3>Próximas entregas</h3><span>HOY</span></div><div className="next-deliveries">{[operations[2],operations[3],operations[0]].map((o,i)=><Link to="/operaciones/$folio" params={{folio:o.folio}} className="next-delivery" key={o.folio}><span className="delivery-number">0{i+1}</span><span><strong>{o.destination.replace('Hospital Regional ','').replace('Hospital General ','')}</strong><small>{o.folio}</small></span><span className="delivery-time">{o.time}<ArrowUpRight size={12}/></span></Link>)}</div><Link className="network-link" to="/mapa-logistico">Explorar mapa logístico<ArrowUpRight size={14}/></Link></>}</>}</aside></div><div className="map-panel-footer"><span><span className="status-dot"/>Cobertura en 32 entidades federativas</span><span>Distribución nacional de medicamentos</span></div></div>;
}
