import { Search, PackageOpen, Check, Circle, ArrowUpRight, ClipboardList, PackageCheck, Warehouse, Truck, MapPin, ShieldCheck, Snowflake, FileClock, PackageMinus } from 'lucide-react';
import { Fragment, type ReactNode } from 'react';
import { operationContext, trackingFor, coldChain, type Operation, type TrackEvent, type EventSource, type AutoAlert } from '@/lib/elia-data';
import { Webhook, PenLine, Cpu, Thermometer, AlertTriangle, Radio } from 'lucide-react';
import { Link } from '@tanstack/react-router';
import { Button } from '@/components/ui/button';
export { Button };
export function PageHeader({eyebrow,title,description,children}:{eyebrow?:string;title:string;description:string;children?:ReactNode}) {return <header className="page-header"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1><p>{description}</p></div>{children&&<div className="header-actions">{children}</div>}</header>}
export function StatusBadge({status}:{status:string}) {const tone=['Crítica','Retrasada','Alta','Error de conexión','Incidencia','Error'].includes(status)?'critical':['Atención','Media','En atención','Sincronización retrasada','Pendiente'].includes(status)?'warning':['Entregada','Entregado','Resuelta','Activo','Normal','Conectado','Registrada'].includes(status)?'success':'info';return <span className={`status-badge ${tone}`}><span className="status-dot"/>{status}</span>}
export function StatBar({items}:{items:{label:string;value:string;note?:string;tone?:string}[]}) {return <div className="stat-bar">{items.map(i=><div className="stat-item" key={i.label}><span className="stat-label">{i.label}</span><div className={`stat-value ${i.tone||''}`}>{i.value}{i.note&&<span className="stat-note">{i.note}</span>}</div></div>)}</div>}
export function SearchBar({value,onChange,placeholder='Buscar por folio, ruta u operador…'}:{value:string;onChange:(v:string)=>void;placeholder?:string}) {return <label className="search-bar"><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
export function FilterTabs({tabs,value,onChange}:{tabs:string[];value:string;onChange:(v:string)=>void}) {return <div className="filter-tabs">{tabs.map(t=><Button key={t} variant="ghost" className={t===value?'filter-active':''} onClick={()=>onChange(t)}>{t}</Button>)}</div>}
export function EmptyState() {return <div className="empty-state"><PackageOpen size={30}/><h3>Sin resultados</h3><p>No hay registros que coincidan con tu búsqueda.</p></div>}
export type Column<T>={label:string;render:(row:T)=>ReactNode;className?:string};
export function DataTable<T>({columns,rows,rowKey}:{columns:Column<T>[];rows:T[];rowKey:(row:T)=>string}) {return <div className="table-scroll"><table className="data-table"><thead><tr>{columns.map(c=><th key={c.label} className={c.className}>{c.label}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={rowKey(r)}>{columns.map(c=><td key={c.label} className={c.className}>{c.render(r)}</td>)}</tr>)}</tbody></table>{rows.length===0&&<EmptyState/>}</div>}
export function ProgressBar({value}:{value:number}) {return <div className="progress-cell"><progress max={100} value={value}/><span>{value}%</span></div>}
export function Person({name,initials}:{name:string;initials:string}) {return <span className="person"><span className="initial-avatar">{initials}</span>{name}</span>}
export function SectionTitle({title,subtitle,children}:{title:string;subtitle?:string;children?:ReactNode}) {return <div className="section-title"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{children}</div>}
const logisticsStages = [{label:'Asignación',icon:ClipboardList},{label:'Recolección',icon:PackageCheck},{label:'Salida',icon:Warehouse},{label:'Traslado',icon:Truck},{label:'Entrega',icon:MapPin},{label:'Validación',icon:ShieldCheck}];
export function LogisticsFlow({operation}:{operation?:Operation}) {const stage=operation?operationContext(operation).stage:-1;return <div className="flow-steps" aria-label="Flujo logístico">{logisticsStages.map((s,i)=><Fragment key={s.label}><div className={`flow-step ${stage<0?'':i<stage?'complete':i===stage?'current':'pending'}`} aria-current={i===stage?'step':undefined}><span className="flow-step-icon"><s.icon/></span><span>{s.label}</span></div>{i<5&&<span className={`flow-line ${i<stage?'complete':''}`}/>}</Fragment>)}</div>}
export function LogisticsTags({operation}:{operation:Operation}) {return <div className="logistics-tags">{operationContext(operation).tags.map(tag=>{const Icon=tag==='Cadena fría'?Snowflake:tag==='Entrega parcial'?PackageMinus:FileClock;return <span className="logistics-tag" key={tag}><Icon size={12}/>{tag}</span>})}</div>}
export function Timeline({operation}:{operation:Operation}) {const {stage,partial}=operationContext(operation);const steps=[['Operación asignada','06:15 h · Coordinación nacional'],['Recolección confirmada',`06:45 h · Almacén de ${operation.origin}`],['Salida de almacén','07:10 h · Documentación validada'],['En tránsito',`12:30 h · ${operation.route}`],[partial?'Recepción parcial':'Llegada',`${operation.time} · ${stage<4?'Estimada':operation.destination}`],['Recepción confirmada',stage===5?`${operation.time} · Evidencia validada`:'Pendiente de validación']];return <ol className="timeline">{steps.map(([title,detail],i)=><li key={title} className={i<stage||stage===5?'complete':i===stage?'current':'pending'}><span className="timeline-icon">{i<stage||stage===5?<Check size={14}/>:<Circle size={12}/>}</span><div><h3>{title}{i===stage&&stage<5&&<span className="live-label">ACTUAL</span>}</h3><p>{detail}</p></div></li>)}</ol>}
export function RowArrow(){return <ArrowUpRight size={16}/>}

const sourceMeta:Record<EventSource,{label:string;icon:typeof Webhook}>={API:{label:'API',icon:Webhook},Manual:{label:'Registro manual',icon:PenLine},ELIA:{label:'Sistema ELIA',icon:Cpu}};
export function SourceBadge({source}:{source:EventSource}){const m=sourceMeta[source];return <span className={`source-badge ${source.toLowerCase()}`}><m.icon size={11}/>{m.label}</span>}
export function SourceLegend(){return <div className="source-legend">{(['API','Manual','ELIA'] as EventSource[]).map(s=><SourceBadge key={s} source={s}/>)}</div>}
export function EventLog({events}:{events:TrackEvent[]}){return <ol className="event-log">{events.map((e,i)=><li key={i} className={`${e.pending?'pending':''} ${e.tone||''}`}><span className="event-time">{e.time}</span><span className="event-node"/><div><strong>{e.title}</strong><small>{e.location}</small></div>{!e.pending&&<SourceBadge source={e.source}/>}</li>)}</ol>}
export function TrackingCard({operation}:{operation:Operation}){const t=trackingFor(operation.folio);return <div className="tracking-card"><div className="tracking-head"><Radio size={14}/><span>Seguimiento unificado</span><StatusBadge status={t.unified}/></div><dl><div><dt>Última ubicación</dt><dd>{t.lastLocation}</dd></div><div><dt>Última actualización</dt><dd>{t.lastUpdate}</dd></div><div><dt>ETA</dt><dd>{t.eta}</dd></div><div><dt>Operador logístico</dt><dd>{t.carrier}</dd></div><div><dt>Fuente del dato</dt><dd>{t.source}</dd></div></dl></div>}
export function ColdChainPanel({folio}:{folio:string}){const c=coldChain[folio];if(!c)return null;const pct=Math.min(100,Math.max(0,(c.reading/12)*100));return <div className={`cold-chain-panel ${c.status==='Crítica'?'critical':''}`}><div className="tracking-head"><Thermometer size={14}/><span>Cadena fría</span><StatusBadge status={c.status}/></div><div className="cold-reading"><strong>{c.current}</strong><span>Rango permitido {c.range}</span></div><div className="cold-scale"><span className="cold-range"/><i style={{left:`${pct}%`}}/></div><small>Última lectura {c.last} · sensor de unidad</small></div>}
export function AlertList({alerts,compact=false}:{alerts:AutoAlert[];compact?:boolean}){return <div className={`alert-list ${compact?'compact':''}`}>{alerts.map((a,i)=><Link key={i} to="/operaciones/$folio" params={{folio:a.folio}} className={`alert-row ${a.severity==='Crítica'?'critical':'attention'}`}><AlertTriangle size={14}/><span><strong>{a.type}</strong><small>{a.detail}</small></span><span className="alert-folio">{a.folio}</span><span className="alert-time">{a.time}</span><StatusBadge status={a.severity}/></Link>)}</div>}
