/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenciasRouteImport } from './routes/evidencias'
import { Route as IncidenciasRouteImport } from './routes/incidencias'
import { Route as IntegracionesRouteImport } from './routes/integraciones'
import { Route as MapaLogisticoRouteImport } from './routes/mapa-logistico'
import { Route as MedicamentosRouteImport } from './routes/medicamentos'
import { Route as OperadoresRouteImport } from './routes/operadores'
import { Route as OperacionesIndexRouteImport } from './routes/operaciones.index'
import { Route as OperacionesFolioRouteImport } from './routes/operaciones.$folio'
import { Route as OperadorIndexRouteImport } from './routes/operador.index'
import { Route as OperadorEvidenciasRouteImport } from './routes/operador.evidencias'
import { Route as OperadorIncidenciasRouteImport } from './routes/operador.incidencias'
import { Route as OperadorServiciosIndexRouteImport } from './routes/operador.servicios.index'
import { Route as OperadorServiciosFolioRouteImport } from './routes/operador.servicios.$folio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenciasRoute = EvidenciasRouteImport.update({
  id: '/evidencias',
  path: '/evidencias',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidenciasRoute = IncidenciasRouteImport.update({
  id: '/incidencias',
  path: '/incidencias',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracionesRoute = IntegracionesRouteImport.update({
  id: '/integraciones',
  path: '/integraciones',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaLogisticoRoute = MapaLogisticoRouteImport.update({
  id: '/mapa-logistico',
  path: '/mapa-logistico',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicamentosRoute = MedicamentosRouteImport.update({
  id: '/medicamentos',
  path: '/medicamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadoresRoute = OperadoresRouteImport.update({
  id: '/operadores',
  path: '/operadores',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacionesIndexRoute = OperacionesIndexRouteImport.update({
  id: '/operaciones/',
  path: '/operaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacionesFolioRoute = OperacionesFolioRouteImport.update({
  id: '/operaciones/$folio',
  path: '/operaciones/$folio',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorIndexRoute = OperadorIndexRouteImport.update({
  id: '/operador/',
  path: '/operador/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorEvidenciasRoute = OperadorEvidenciasRouteImport.update({
  id: '/operador/evidencias',
  path: '/operador/evidencias',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorIncidenciasRoute = OperadorIncidenciasRouteImport.update({
  id: '/operador/incidencias',
  path: '/operador/incidencias',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorServiciosIndexRoute = OperadorServiciosIndexRouteImport.update({
  id: '/operador/servicios/',
  path: '/operador/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorServiciosFolioRoute = OperadorServiciosFolioRouteImport.update({
  id: '/operador/servicios/$folio',
  path: '/operador/servicios/$folio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidencias': typeof EvidenciasRoute
  '/incidencias': typeof IncidenciasRoute
  '/integraciones': typeof IntegracionesRoute
  '/mapa-logistico': typeof MapaLogisticoRoute
  '/medicamentos': typeof MedicamentosRoute
  '/operadores': typeof OperadoresRoute
  '/operaciones/$folio': typeof OperacionesFolioRoute
  '/operador/evidencias': typeof OperadorEvidenciasRoute
  '/operador/incidencias': typeof OperadorIncidenciasRoute
  '/operaciones/': typeof OperacionesIndexRoute
  '/operador/': typeof OperadorIndexRoute
  '/operador/servicios/$folio': typeof OperadorServiciosFolioRoute
  '/operador/servicios/': typeof OperadorServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidencias': typeof EvidenciasRoute
  '/incidencias': typeof IncidenciasRoute
  '/integraciones': typeof IntegracionesRoute
  '/mapa-logistico': typeof MapaLogisticoRoute
  '/medicamentos': typeof MedicamentosRoute
  '/operadores': typeof OperadoresRoute
  '/operaciones/$folio': typeof OperacionesFolioRoute
  '/operador/evidencias': typeof OperadorEvidenciasRoute
  '/operador/incidencias': typeof OperadorIncidenciasRoute
  '/operaciones': typeof OperacionesIndexRoute
  '/operador': typeof OperadorIndexRoute
  '/operador/servicios/$folio': typeof OperadorServiciosFolioRoute
  '/operador/servicios': typeof OperadorServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidencias': typeof EvidenciasRoute
  '/incidencias': typeof IncidenciasRoute
  '/integraciones': typeof IntegracionesRoute
  '/mapa-logistico': typeof MapaLogisticoRoute
  '/medicamentos': typeof MedicamentosRoute
  '/operadores': typeof OperadoresRoute
  '/operaciones/$folio': typeof OperacionesFolioRoute
  '/operador/evidencias': typeof OperadorEvidenciasRoute
  '/operador/incidencias': typeof OperadorIncidenciasRoute
  '/operaciones/': typeof OperacionesIndexRoute
  '/operador/': typeof OperadorIndexRoute
  '/operador/servicios/$folio': typeof OperadorServiciosFolioRoute
  '/operador/servicios/': typeof OperadorServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evidencias'
    | '/incidencias'
    | '/integraciones'
    | '/mapa-logistico'
    | '/medicamentos'
    | '/operadores'
    | '/operaciones/$folio'
    | '/operador/evidencias'
    | '/operador/incidencias'
    | '/operaciones/'
    | '/operador/'
    | '/operador/servicios/$folio'
    | '/operador/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evidencias'
    | '/incidencias'
    | '/integraciones'
    | '/mapa-logistico'
    | '/medicamentos'
    | '/operadores'
    | '/operaciones/$folio'
    | '/operador/evidencias'
    | '/operador/incidencias'
    | '/operaciones'
    | '/operador'
    | '/operador/servicios/$folio'
    | '/operador/servicios'
  id:
    | '__root__'
    | '/'
    | '/evidencias'
    | '/incidencias'
    | '/integraciones'
    | '/mapa-logistico'
    | '/medicamentos'
    | '/operadores'
    | '/operaciones/$folio'
    | '/operador/evidencias'
    | '/operador/incidencias'
    | '/operaciones/'
    | '/operador/'
    | '/operador/servicios/$folio'
    | '/operador/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenciasRoute: typeof EvidenciasRoute
  IncidenciasRoute: typeof IncidenciasRoute
  IntegracionesRoute: typeof IntegracionesRoute
  MapaLogisticoRoute: typeof MapaLogisticoRoute
  MedicamentosRoute: typeof MedicamentosRoute
  OperadoresRoute: typeof OperadoresRoute
  OperacionesFolioRoute: typeof OperacionesFolioRoute
  OperadorEvidenciasRoute: typeof OperadorEvidenciasRoute
  OperadorIncidenciasRoute: typeof OperadorIncidenciasRoute
  OperacionesIndexRoute: typeof OperacionesIndexRoute
  OperadorIndexRoute: typeof OperadorIndexRoute
  OperadorServiciosFolioRoute: typeof OperadorServiciosFolioRoute
  OperadorServiciosIndexRoute: typeof OperadorServiciosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidencias': {
      id: '/evidencias'
      path: '/evidencias'
      fullPath: '/evidencias'
      preLoaderRoute: typeof EvidenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidencias': {
      id: '/incidencias'
      path: '/incidencias'
      fullPath: '/incidencias'
      preLoaderRoute: typeof IncidenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integraciones': {
      id: '/integraciones'
      path: '/integraciones'
      fullPath: '/integraciones'
      preLoaderRoute: typeof IntegracionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-logistico': {
      id: '/mapa-logistico'
      path: '/mapa-logistico'
      fullPath: '/mapa-logistico'
      preLoaderRoute: typeof MapaLogisticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicamentos': {
      id: '/medicamentos'
      path: '/medicamentos'
      fullPath: '/medicamentos'
      preLoaderRoute: typeof MedicamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operadores': {
      id: '/operadores'
      path: '/operadores'
      fullPath: '/operadores'
      preLoaderRoute: typeof OperadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operaciones/': {
      id: '/operaciones/'
      path: '/operaciones'
      fullPath: '/operaciones/'
      preLoaderRoute: typeof OperacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operaciones/$folio': {
      id: '/operaciones/$folio'
      path: '/operaciones/$folio'
      fullPath: '/operaciones/$folio'
      preLoaderRoute: typeof OperacionesFolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/': {
      id: '/operador/'
      path: '/operador'
      fullPath: '/operador/'
      preLoaderRoute: typeof OperadorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/evidencias': {
      id: '/operador/evidencias'
      path: '/operador/evidencias'
      fullPath: '/operador/evidencias'
      preLoaderRoute: typeof OperadorEvidenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/incidencias': {
      id: '/operador/incidencias'
      path: '/operador/incidencias'
      fullPath: '/operador/incidencias'
      preLoaderRoute: typeof OperadorIncidenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/servicios/': {
      id: '/operador/servicios/'
      path: '/operador/servicios'
      fullPath: '/operador/servicios/'
      preLoaderRoute: typeof OperadorServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/servicios/$folio': {
      id: '/operador/servicios/$folio'
      path: '/operador/servicios/$folio'
      fullPath: '/operador/servicios/$folio'
      preLoaderRoute: typeof OperadorServiciosFolioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenciasRoute: EvidenciasRoute,
  IncidenciasRoute: IncidenciasRoute,
  IntegracionesRoute: IntegracionesRoute,
  MapaLogisticoRoute: MapaLogisticoRoute,
  MedicamentosRoute: MedicamentosRoute,
  OperadoresRoute: OperadoresRoute,
  OperacionesFolioRoute: OperacionesFolioRoute,
  OperadorEvidenciasRoute: OperadorEvidenciasRoute,
  OperadorIncidenciasRoute: OperadorIncidenciasRoute,
  OperacionesIndexRoute: OperacionesIndexRoute,
  OperadorIndexRoute: OperadorIndexRoute,
  OperadorServiciosFolioRoute: OperadorServiciosFolioRoute,
  OperadorServiciosIndexRoute: OperadorServiciosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
